### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#119]
### Metrics to track

**Message Sarah for login credentials.**

**Please include device type as a parameter in all requests.**

| GA Event Name | GA Event Properties |
|-|-|
| User clicked a state in the state list | Name of state clicked | 
| User clicked a state on the map | Name of state clicked |
| User opened Glossary |
| User opened Scoring Guide |
| User opened Methodology |
| User opened Partner with FreeFrom form |
| User submitted Partner with FreeFrom form |
| User opened Build Collective Survivor Power form |
| User submitted Build Collective Survivor Power form |
| User opened Share Your Policy Ideas form |
| User submitted Share Your Policy Ideas form |
| User opened Give Feedback form |
| User submitted Give Feedback form |
| User opened Subscribe to State Updates form | Current page (home or state) |
| User submitted Subscribe to State Updates form | Current page (home or state) |
| User opened Report Missing/Outdated Information form | Current page (home or state) |
| User submitted Report Missing/Outdated Information form | Current page (home or state) |
| User clicked "Share" button from homepage | Current page (home or state) |
| User clicked "Share" button from state page | Current page (home or state) |

**Comment by Ragtag-Laura** [comment]
Partner shared their Google Analytics credentials on 3/23 but no metrics yet. Will follow-up.

**Comment by DanielKim1** [comment]
Measurement ID is available as `process.env.GA_MEASUREMENT_ID` on freefrom-map-frontend-prod (Set using `heroku config`. See https://devcenter.heroku.com/articles/config-vars.)

**Comment by sarahgreen** [comment]
Leaving a note to myself to tell FF we aren't going to try to track the `most searched state`. It's too hard to define this. Perhaps we could store the text the user entered into the box and include that in a GA event, but how often should the event fire? Every time the user adds/removes a character from the search box? And how would we list out the results if more than one state matched the text searched?
