### ISSUE TITLE
Add survivor quote to state page

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#160]
See corresponding backend change: https://github.com/RagtagOpen/freefrom-map-backend/issues/127

**Comment by Ragtag-Laura** [comment]
3/23 note from partner:
Sarah asked me to flag some of the lower priority items since there are a lot of changes on deck. After reviewing, the quotes on each state's page and the color-changes to the subpages are our two lower-priority items that can maybe be tackled after launch if necessary.
