### ISSUE TITLE
Reformat Take Action links as image blocks

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#163]
Finalized design:
<img width="514" alt="Take Action" src="https://user-images.githubusercontent.com/6788487/113895974-586acd80-977e-11eb-8b80-ad147bf5869d.png">

Images have been added to the public/images/take-action folder.

**Comment by Ragtag-Laura** [comment]
3/23 note from partner:
The following are now in the Dropbox: Images for the Take Action buttons
