### ISSUE TITLE
Replace "States to Watch" content with real content

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#169]
Requires FreeFrom to share this content with us

**Comment by Ragtag-Laura** [comment]
3/23 note from partner:
The following are now in the Dropbox: ... State outlines for the States to Watch

Content for States to Watch (headline text above the image and the description text below it) is still being finalized. Sabrina will send it over once it's ready.

**Comment by Ragtag-Laura** [comment]
3/26 note from partner:
Circling back to say that we finished up the mock-up for the individual States page below. You can find it in the Design Polish Figma file, (Screenshot below for reference.) Let me know if you have any questions or if it's easier to address any issues on our next call, that works for me as well.
<img width="151" alt="States Page Mobile Mock" src="https://user-images.githubusercontent.com/53442476/112752204-d28d9c00-8f9f-11eb-986b-b853769d1e43.png">
