### ISSUE TITLE
Mobile/Safari display issues - state page

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#172]
**SEE ALSO #143**

### Desktop Small Window - State Page
<img width="935" alt="state page layout issues small window" src="https://user-images.githubusercontent.com/6788487/110850516-b7fbb900-8264-11eb-9f25-ad9b6d825e83.png">

### Mobile - State Page
![mobile state scorecard is not readable](https://user-images.githubusercontent.com/6788487/110850626-da8dd200-8264-11eb-9a49-c8e671cc78b1.png)

### Safari - State Page
<img width="1290" alt="Screen Shot 2021-04-05 at 11 47 34 PM" src="https://user-images.githubusercontent.com/6788487/113669974-5e22bf00-9669-11eb-84de-05e43eaca670.png">

**Comment by Ragtag-Laura** [comment]
3/23 note from partner (Tiffany):
I'm working on mobile mockups for both the Homepage and the individual States page, to hopefully help ease some of the trickier design work off of these sections. Wanted to flag that so y'all don't spend too much on the mobile versions of these pages. Hoping to finish working on those ASAP.

**Comment by sarahgreen** [comment]
@egiurleo I took a bad shortcut and tested with Chrome tools rather than mirroring my local on my phone... Looks like we still have issues on mobile with the state page :(

![IMG_0675](https://user-images.githubusercontent.com/6788487/113597855-28da8a80-95f1-11eb-90be-765283293a4e.PNG)

![IMG_0676](https://user-images.githubusercontent.com/6788487/113597867-2c6e1180-95f1-11eb-8ba3-2251cad997f2.PNG)

**Comment by egiurleo** [comment]
@sarahgreen Okay gonna look at this now!
