### ISSUE TITLE
Optimize left/right page margins for all screens

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#175]
FreeFrom would like wider left/right page margins for desktop, but also to minimize wasted space on small screens so the list/map still look good. Can we find a middle ground?

**Comment by Ragtag-Laura** [comment]
3/23 note from partner:
We wanted to circle back on how possible it would be to widen the margins of the desktop version of the map without sacrificing the margins necessary for mobile. If we could do two different page widths, we'd love to do 1250px for the width of the page for desktop and 300px for mobile. Let me know if that works!
