### ISSUE TITLE
Work with FreeFrom to point a subdomain of freefrom.org to the production site

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#219]
This will need to be done ahead of launch and once the production site is fully set up & tested.

Subdomain: mapandscorecard.freefrom.org
FreeFrom Contact: Diana

**Comment by DanielKim1** [comment]
Need DNS target from FreeFrom
https://dashboard.heroku.com/apps/freefrom-map-frontend-prod/settings
https://ragtag-team.slack.com/archives/C018U9NNLAF/p1618002642130000

**Comment by sarahgreen** [comment]
Just documenting here that we got the DNS target via Heroku: guarded-bass-w1g8weews3gjpcgr0o7tfl58.herokudns.com. I'm going to meet with FF's site admin next week to try to set up the new CNAME.
