### ISSUE TITLE
Create shell for forms & form pages

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#41]

**Comment by grantstromgren** [comment]
@sarahgreen Can you fill out some details here? Is this just a reusable component for any forms?

**Comment by sarahgreen** [comment]
@grantstromgren I'm actually not exactly sure. What I know is that we'll want to build out several forms that should have consistent styling for the different types of questions (text, single select, multiselect) and buttons. And, one form will submit to a third-party API and the rest will submit to various Google Sheets. The idea of this ticket is to do any preliminary work that will enable the team to work on these various forms in parallel.

**Comment by egiurleo** [comment]
@sarahgreen can you remind me what form is submitting to a third-party API?

**Comment by sarahgreen** [comment]
@egiurleo The Contact Your Legislators form — I think we decided we’ll get the zip code from the user and send it over to this API to get the legislator info: https://docs.mapbox.com/api/search/#forward-geocoding

**Comment by egiurleo** [comment]
RIGHT. Okay I will work on backend endpoints for this stuff :)
