### ISSUE TITLE
Set up frontend deployments

### ISSUE THREAD

**Issue by egiurleo** [RagtagOpen/freefrom-map-frontend#77]
It would be helpful for the FreeFrom team to be able to see the state of this project without any special tech setup. We should deploy the frontend somewhere and have it update every time we merge to GitHub.

**Comment by DanielKim1** [comment]
The good news is that this is now done:
- https://app.circleci.com/pipelines/github/RagtagOpen/freefrom-map-frontend
- https://freefrom-map-frontend.herokuapp.com/

However, I had to `git pull heroku main` from the staging branch. I think that got us out of git hell, but unfortunately the git history is now all gross looking:
https://github.com/RagtagOpen/freefrom-map-frontend/commits/staging

Sorry about that 🙏
