### ISSUE TITLE
Hovercard blocks modal

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-frontend#81]
**Current behavior:**
When the hovercard on the map has been activated, if you open a modal, the hovercard will block it.

**Expected behavior:**
If you open a modal, the hovercard should disappear.

https://user-images.githubusercontent.com/6788487/108300384-1695b180-7155-11eb-8ff8-8f3d55ae4173.mov

**Comment by landonreed** [comment]
This should be fixed in 5d77bd971f1d3edfd1eff38d49bc492715248fc0 (part of #94).
